### PR TITLE
Add TeslaMate

### PR DESCRIPTION
**Pull request by lildude**
Add TeslaMate

### CODE REVIEW

**Comment by DukeMini** [comment]
Thank you for taking over the maintenance of the TeslaMate integration. I have seen that you have also included the PostgreSQL addon in your repository. Can't you also officially reference the PostgeSQL in https://github.com/alexbelgium/hassio-addons?

In that case, the DB is always up to date. I have my TeslaMate running with this version without any problems.

**Comment by lildude** [comment]
You're free to use any DB you like and I've stated it in the docs. I'm only using the Postgres that was previously included with the TeslaMate add-on as that's the one I use and have tested with.

**Comment by shivaagarwal1** [comment]
Hi lildude. Is there a time line to add Teslamate add-on to this repository? I added your add-on repository, but Teslamate is not available in it. Thank you.

**Comment by lildude** [comment]
No time line. I plan to merge as soon as I've had a chance to properly test it... I've been really short of free time recently but things should hopefully ease up over the next week or so.

**Comment by shivaagarwal1** [comment]
> No time line. I plan to merge as soon as I've had a chance to properly test it... I've been really short of free time recently but things should hopefully ease up over the next week or so.

Thank you for your quick reply.

**Comment by lildude** [comment]
Testing confirms all working well.

**Comment by shivaagarwal1** [comment]
Amazing. Just downloaded and everything working well. Thank you again for your hard work on this.

**Pull request merged**
